###############################################################################
# (c) Copyright 2000-2018 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
stages:
  - check
  - docs
  - deploy

variables:
  TARGET_BRANCH: master

check-copyright:
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  stage: check
  script:
    - curl -o lb-check-copyright "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/SourceTools.py?inline=false"
    - python lb-check-copyright origin/${TARGET_BRANCH}
check-formatting:
  image: gitlab-registry.cern.ch/lhcb-docker/style-checker
  stage: check
  script:
    - if [ ! -e .clang-format ] ; then
    -   curl -o .clang-format "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/data/default.clang-format?inline=false"
    -   echo '.clang-format' >> .gitignore
    -   git add .gitignore
    - fi
    - curl -o lb-format "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/SourceTools.py?inline=false"
    - python lb-format --format-patch apply-formatting.patch origin/${TARGET_BRANCH}
  artifacts:
    paths:
      - apply-formatting.patch
    when: on_failure
    expire_in: 1 week

# inspired by https://gitlab.cern.ch/lhcb/Moore/-/blob/master/.gitlab-ci.yml      
build-docs:
  stage: docs
  image: gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" || $CI_MERGE_REQUEST_LABELS =~ /Documentation/' 
  tags:
    - cvmfs
  script:
    - . /cvmfs/lhcb.cern.ch/lib/LbEnv.sh
    - reasons=
    - make -C docs html || reasons+='ERROR failed html generation\n'
    - if [ -n "$reasons" ]; then echo -e $reasons; exit 1; fi
  allow_failure:
    exit_codes: 77
  artifacts:
    paths:
      - docs/_build/html/

# inspired by https://gitlab.cern.ch/lhcb/Moore/-/blob/master/.gitlab-ci.yml      
deploy-docs:
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" || $CI_MERGE_REQUEST_LABELS =~ /Documentation/' 
  variables:
    EOS_PATH: "/eos/user/m/mimazure/www/test-gaussino-docs/$CI_COMMIT_REF_NAME" #FIXME: for testing
    CI_OUTPUT_DIR: "docs/_build/html"
    METHOD: "rsync"
  before_script:
    # As the previous stage is allowed to fail, skip this stage if the previous
    # did not complete successfully (i.e. did not create the html directory)
    - test -d $CI_OUTPUT_DIR || { echo "WARNING docs not built, stopping"; exit 77; }
  script:
    - deploy-eos && echo -e "Deployed at\n\n\t/eos/user/m/mimazure/www/test-gaussino-docs/$CI_COMMIT_REF_NAME/index.html"
  allow_failure:
    exit_codes: 77

