# Special toolchain file that inherits the same heptools version as the
# used projects.
find_file(inherit_heptools_module InheritHEPTools.cmake)

if(EXISTS ${CMAKE_SOURCE_DIR}/generators_versions.txt)
  file(READ ${CMAKE_SOURCE_DIR}/generators_versions.txt generators_versions)
  string(REGEX REPLACE "[ \t\n]+" ";" generators_versions "${generators_versions}")
  set(generators_versions ${generators_versions})
endif()

# Process the lines of LCG_generators_*.txt file to extract the
# needed generators (variable generators_versions)
macro(lcg_set_generator root name hash version dir)
  #message(STATUS "Processing ${name} ${version} (${dir})")
  list(FIND generators_versions ${name} _gen_idx)
  list(FIND found_generators ${name} _found_idx)
  if(NOT _gen_idx EQUAL -1 AND _found_idx EQUAL -1)
    math(EXPR _gen_vers_idx "${_gen_idx} + 1")
    list(GET generators_versions ${_gen_vers_idx} _gen_vers)
    #message(STATUS "  required ${_gen_vers}")
    if("${version}" STREQUAL "${_gen_vers}")
      set(${name}_native_version ${${name}_config_version})
      if(NOT IS_ABSOLUTE ${dir})
        set(${name}_home ${root}/${dir})
      else()
        set(${name}_home ${dir})
      endif()
      if(EXISTS ${${name}_home})
        get_filename_component(${name}_home "${${name}_home}" ABSOLUTE)
        set(${name}_config_version ${version} CACHE STRING "Version of ${name}")
        mark_as_advanced(${name}_config_version)
        #message(STATUS "Using ${name} ${version} from ${${name}_home}")
        list(INSERT CMAKE_PREFIX_PATH 0 ${${name}_home})
        list(APPEND found_generators ${name})
      endif()
    #else()
    #  message(STATUS "  wrong version (${name} ${version})")
    endif()
  #else()
  #  if(_found_idx EQUAL -1)
  #    message(STATUS "  ${name} not required")
  #  else()
  #    message(STATUS "  ${name} already found")
  #  endif()
  endif()
endmacro()

# Check that all the generators in generators_versions are found in the
# LCG_generators_*.txt file.
macro(check_generators)
  set(_idx 0)
  set(_missing_generators)
  list(LENGTH generators_versions _length)
  while(_idx LESS _length)
    list(GET generators_versions ${_idx} _gen_name)
    list(FIND found_generators ${_gen_name} _found_idx)
    if(_found_idx EQUAL -1)
      math(EXPR _gen_vers_idx "${_idx} + 1")
      list(GET generators_versions ${_gen_vers_idx} _gen_ver)
      set(_missing_generators "${_missing_generators} ${_gen_name}(${_gen_ver})")
    endif()
    math(EXPR _idx "${_idx} + 2")
  endwhile()
  if(_missing_generators)
    message(WARNING "Missing generators: ${_missing_generators}")
  endif()
endmacro()

# this check is needed because the toolchain seem to be called a second time
# without the proper cache
if(inherit_heptools_module)
  include(${inherit_heptools_module})
  inherit_heptools()
  set(BINARY_TAGCOMP ${BINARY_TAG})
  if(BINARY_TAG STREQUAL "x86_64-centos7-gcc7-do0")
    set(BINARY_TAGCOMP "x86_64-centos7-gcc7-dbg")
  endif()

  message(STATUS "BINARY_TAGCOMP=${BINARY_TAGCOMP}")
  message(STATUS "BINARY_TAG=${BINARY_TAG}")

  if(LCG_TOOLCHAIN_INFO)
    # prepare list of toolchain info files for generators
    set(_info_name "LCG_generators_${BINARY_TAGCOMP}.txt")
    # look for alternative info files
    file(TO_CMAKE_PATH "$ENV{CMAKE_PREFIX_PATH}" _a)
    file(TO_CMAKE_PATH "$ENV{CMTPROJECTPATH}" _b)
    set(_search_path ${LCG_releases} ${_a} ${_b} ${CMAKE_PREFIX_PATH})
    foreach(_d ${_search_path})
      foreach(_suff "LCG_${heptools_version}" ".")
        foreach(_f "${_d}/${_suff}/${_info_name}.installed"
                   "${_d}/${_suff}/${_info_name}")
          if(EXISTS "${_f}")
            get_filename_component(_f "${_f}" ABSOLUTE)
            list(APPEND LCG_GENERATOR_INFOS "${_f}")
            break()
          endif()
        endforeach()
      endforeach()
    endforeach()
    if(NOT LCG_GENERATOR_INFOS)
      message(FATAL_ERROR "Generators infos not found for ${heptools_version}")
    endif()
    message(STATUS "Using generators infos from:")
    list(REMOVE_DUPLICATES LCG_GENERATOR_INFOS)
    foreach(_i ${LCG_GENERATOR_INFOS})
      message(STATUS "  * ${_i}")
    endforeach()

    set(found_generators)
    foreach(_i ${LCG_GENERATOR_INFOS})
      get_filename_component(_info_dir "${_i}" PATH)
      file(STRINGS "${_i}" _lcg_infos)
      foreach(_l ${_lcg_infos})
        if(NOT _l MATCHES "^(PLATFORM|VERSION|COMPILER):")
          string(REGEX REPLACE "; *" ";" _l "${_l}")
          lcg_set_generator(${_info_dir} ${_l})
        endif()
      endforeach()
    endforeach()
    check_generators()
  else()
    # This check is to handle the special case of test builds internal to CMake
    if(NOT CMAKE_SOURCE_DIR MATCHES "CMakeTmp")
      message(FATAL_ERROR "Only LCG >= 68 is supported")
    endif()
  endif()
endif()

if(DEFINED ENV{LBLOCALSOFT})
  message(STATUS "Manually prepending $ENV{LBLOCALSOFT} to CMAKE_PREFIX_PATH")
  set(CMAKE_PREFIX_PATH "$ENV{LBLOCALSOFT};${CMAKE_PREFIX_PATH}")
endif()

# FIXME: make sure we do not pick up geant from LCG (it requires LD_LIBRARY_PATH set)
if(CMAKE_PREFIX_PATH AND CMAKE_VERSION VERSION_GREATER "3.6.0")
  list(FILTER CMAKE_PREFIX_PATH EXCLUDE REGEX "(LCG_|lcg/nightlies).*Geant4")
endif()

set(CMAKE_PREFIX_PATH /cvmfs/sft.cern.ch/lcg/releases/LCG_${heptools_version}/hepmc3/3.0.0/${BINARY_TAGCOMP} ${CMAKE_PREFIX_PATH})                                                                                                                            
